// Декларативные спецификации предпросмотра шаблонов.
// Механически перенесено из getTemplatePreview (DocumentPreview.tsx) с сохранением
// поведения 1-в-1. Порядок записей и строк соответствует порядку в исходной функции.
//
// Составные строки (несколько getFieldValue и/или текст между ними) выражены через
// kind:'tpl' с плейсхолдерами {имяПоля}.

export type PreviewRow =
  | { kind: 'field'; label: string; field: string; unit?: string }
  | { kind: 'count'; label: string }
  | { kind: 'contract'; label: string; numberField: string; dateField: string }
  // Составная строка: `template` с плейсхолдерами `{имяПоля}` подставляется через
  // getFieldValue, остальной текст — как есть. Покрывает «{inn} / {ogrnip}»,
  // «… руб., проценты … руб., неустойка … руб.» и т.п.
  | { kind: 'tpl'; label: string; template: string }
  | { kind: 'text'; text: string };

export interface TemplatePreviewSpec {
  id: string;
  title: string;
  rows: PreviewRow[];
}

export const TEMPLATE_PREVIEW_SPECS: TemplatePreviewSpec[] = [
  {
    id: 'rtk_single_obligation',
    title: 'Решение о включении в РТК (одно обязательство)',
    rows: [
      // Строки «В Арбитражный суд города Москвы» здесь не было места: суд в
      // предпросмотре был вписан намертво и не имел отношения к делу (акты идут
      // в Арбитражный суд Ростовской области). Убрана по требованию Андрея.
      { kind: 'field', label: 'ФИО должника:', field: 'applicantName' },
      { kind: 'field', label: 'Адрес должника:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt', unit: 'руб.' },
      { kind: 'field', label: 'Ссудная задолженность:', field: 'loanDebt', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest', unit: 'руб.' },
      { kind: 'field', label: 'Штрафные санкции:', field: 'penalties', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'field', label: 'Кредитор:', field: 'creditorName' },
      { kind: 'field', label: 'Должник:', field: 'debtorName' },
    ],
  },
  {
    id: 'rtk_multiple_obligations',
    title: 'Решение о включении в РТК (несколько обязательств)',
    rows: [
      // См. rtk_single_obligation: захардкоженный московский суд убран.
      { kind: 'field', label: 'ФИО должника:', field: 'applicantName' },
      { kind: 'field', label: 'Адрес должника:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt', unit: 'руб.' },
      { kind: 'field', label: 'Ссудная задолженность:', field: 'loanDebt', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest', unit: 'руб.' },
      { kind: 'field', label: 'Штрафные санкции:', field: 'penalties', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
    ],
  },
  {
    // Ветка observation_single || observation_multiple: заголовок зависит от id,
    // развёрнут в отдельные записи со статическими title.
    id: 'observation_single',
    title: 'Наблюдение — комплект судебных актов (одно обязательство)',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: основное определение, резолютивная часть и определение о принятии требований.' },
    ],
  },
  {
    id: 'observation_multiple',
    title: 'Наблюдение — комплект судебных актов (несколько обязательств)',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: основное определение, резолютивная часть и определение о принятии требований.' },
    ],
  },
  {
    id: 'observation_collateral',
    title: 'Наблюдение с залогом — комплект судебных актов',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: принятие РТК наблюдение, наблюдение ВКЛ в РТК с залогом.' },
    ],
  },
  {
    id: 'competition_collateral',
    title: 'Конкурсное производство с залогом — комплект судебных актов',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: принятие РТК конкурсное, конкурсное ВКЛ в РТК с залогом.' },
    ],
  },
  {
    id: 'initiation_physical',
    title: 'Инициирование банкротства физического лица',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дата рождения:', field: 'birthDate' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Сумма задолженности:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'field', label: 'ИНН:', field: 'inn' },
      { kind: 'text', text: 'В комплект входят: принятие заявления, определение о введении реструктуризации долгов, определение о введении реализации имущества.' },
    ],
  },
  {
    id: 'kfh_observation',
    title: 'КФХ — комплект судебных актов (наблюдение)',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Глава КФХ:', field: 'kfhHeadName' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: принятие и инициирование КФХ, наблюдение КФХ.' },
    ],
  },
  {
    id: 'kfh_observation_collateral',
    title: 'КФХ с залогом — комплект судебных актов (наблюдение с залогом)',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Глава КФХ:', field: 'kfhHeadName' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'count', label: 'Количество обязательств:' },
      { kind: 'text', text: 'В комплект входят: принятие и инициирование КФХ (залог), наблюдение КФХ залог.' },
    ],
  },
  {
    id: 'deceased',
    title: 'Умерший — комплект судебных актов',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Суд:', field: 'courtName' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Сумма требований:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: принятие заявления о признании должника банкротом умерший, решение умерший.' },
    ],
  },
  {
    id: 'ip_collection',
    title: 'Взыскания ИП',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'field', label: 'Сумма кредита:', field: 'creditAmount', unit: 'руб.' },
      { kind: 'field', label: 'Срок кредита:', field: 'creditTermMonths', unit: 'мес.' },
      { kind: 'field', label: 'Процентная ставка:', field: 'creditInterestRate', unit: '%' },
      { kind: 'field', label: 'Ставка неустойки:', field: 'creditPenaltyRate', unit: '%' },
      { kind: 'field', label: 'Дата расчета задолженности:', field: 'debtSnapshotDate' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Комиссия Банка:', field: 'bankCommission', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение взыскание с ИП, Принятие иска о взыскании с ИП.' },
    ],
  },
  {
    id: 'ip_collection_collateral',
    title: 'Взыскания ИП + Залог',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Сумма кредита:', field: 'creditAmount', unit: 'руб.' },
      { kind: 'field', label: 'Срок кредита:', field: 'creditTermMonths', unit: 'мес.' },
      { kind: 'field', label: 'Процентная ставка:', field: 'creditInterestRate', unit: '%' },
      { kind: 'field', label: 'Ставка неустойки:', field: 'creditPenaltyRate', unit: '%' },
      { kind: 'field', label: 'Дата расчета задолженности:', field: 'debtSnapshotDate' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Комиссия Банка:', field: 'bankCommission', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение о взысканнии с ИП залог, Принятие иска о взыскании с ИП Залог.' },
    ],
  },
  {
    id: 'ip_collection_collateral_auto',
    title: 'Взыскание ИП залог авто',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога (авто) [1221]:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Сумма кредита:', field: 'creditAmount', unit: 'руб.' },
      { kind: 'field', label: 'Срок кредита:', field: 'creditTermMonths', unit: 'мес.' },
      { kind: 'field', label: 'Процентная ставка:', field: 'creditInterestRate', unit: '%' },
      { kind: 'field', label: 'Ставка неустойки:', field: 'creditPenaltyRate', unit: '%' },
      { kind: 'field', label: 'Дата расчета задолженности:', field: 'debtSnapshotDate' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Комиссия Банка:', field: 'bankCommission', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение о взыскании с ИП залог авто, Принятие иска о взыскании с ИП залог авто.' },
    ],
  },
  {
    id: 'legal_collection',
    title: 'Взыскание с ЮЛ',
    rows: [
      { kind: 'field', label: 'Организация:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРН:', template: '{inn} / {ogrn}' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение о взыскании с ЮЛ, Принятие иска о взыскании с ЮЛ.' },
    ],
  },
  {
    id: 'legal_collection_collateral',
    title: 'Взыскание с ЮЛ + Залог',
    rows: [
      { kind: 'field', label: 'Организация:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРН:', template: '{inn} / {ogrn}' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение о взыскании с ЮЛ Залог, Принятие иска о взыскании с ЮЛ Залог.' },
    ],
  },
  {
    id: 'legal_collection_collateral_auto',
    title: 'Взыскание с ЮЛ залог авто',
    rows: [
      { kind: 'field', label: 'Организация:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРН:', template: '{inn} / {ogrn}' },
      { kind: 'field', label: 'Юридический адрес:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога (авто):', field: 'mortgageCollateralDescription1221' },
      { kind: 'field', label: 'Основной долг:', field: 'principalDebt13', unit: 'руб.' },
      { kind: 'field', label: 'Проценты:', field: 'interest14', unit: 'руб.' },
      { kind: 'field', label: 'Неустойка:', field: 'forfeit15', unit: 'руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'field', label: 'Общая сумма долга:', field: 'totalDebt', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: Решение о взыскании с ЮЛ Залог авто, Принятие иска о взыскании с ЮЛ Залог авто.' },
    ],
  },
  {
    // Ветка ip_enforcement_realization || ip_enforcement_restructuring:
    // заголовок = id.includes('realization') ? 'реализация' : 'реструктуризация'.
    id: 'ip_enforcement_realization',
    title: 'Взыскание с индивидуального предпринимателя (реализация)',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'tpl', label: 'Условия кредита:', template: '{creditAmount} руб., срок {creditTermMonths} мес., ставка {creditInterestRate} %' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: принятие иска о взыскании с ИП, решение взыскание с ИП.' },
    ],
  },
  {
    id: 'ip_enforcement_restructuring',
    title: 'Взыскание с индивидуального предпринимателя (реструктуризация)',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'tpl', label: 'Условия кредита:', template: '{creditAmount} руб., срок {creditTermMonths} мес., ставка {creditInterestRate} %' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: принятие иска о взыскании с ИП, решение взыскание с ИП.' },
    ],
  },
  {
    // Ветка *_collateral: procedureType = id.includes('realization') ? 'реализация' : 'реструктуризация';
    // заголовок = «… ({procedureType} с залогом)».
    id: 'ip_enforcement_realization_collateral',
    title: 'Взыскание с индивидуального предпринимателя (реализация с залогом)',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: принятие РТК с залогом, решение о включении в РТК с залогом, резолютивная часть.' },
    ],
  },
  {
    id: 'ip_enforcement_restructuring_collateral',
    title: 'Взыскание с индивидуального предпринимателя (реструктуризация с залогом)',
    rows: [
      { kind: 'field', label: 'ИП:', field: 'applicantName' },
      { kind: 'tpl', label: 'ИНН / ОГРНИП:', template: '{inn} / {ogrnip}' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'field', label: 'Госпошлина:', field: 'stateDuty16', unit: 'руб.' },
      { kind: 'text', text: 'В комплект входят: принятие РТК с залогом, решение о включении в РТК с залогом, резолютивная часть.' },
    ],
  },
  {
    id: 'physical_realization_collateral',
    title: 'Реализация имущества физического лица с залогом',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дата рождения:', field: 'birthDate' },
      { kind: 'field', label: 'СНИЛС:', field: 'snils' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'text', text: 'В комплект входят: принятие РТК с залогом, решение о включении в РТК с залогом, резолютивная часть.' },
    ],
  },
  {
    id: 'physical_restructuring_collateral',
    title: 'Реструктуризация долгов физического лица с залогом',
    rows: [
      { kind: 'field', label: 'Должник:', field: 'applicantName' },
      { kind: 'field', label: 'Адрес регистрации:', field: 'applicantAddress' },
      { kind: 'field', label: 'Дата рождения:', field: 'birthDate' },
      { kind: 'field', label: 'СНИЛС:', field: 'snils' },
      { kind: 'field', label: 'Дело №:', field: 'caseNumber' },
      { kind: 'contract', label: 'Кредитный договор:', numberField: 'contractNumber', dateField: 'contractDate' },
      { kind: 'contract', label: 'Договор залога:', numberField: 'ipCollateralContractNumber', dateField: 'ipCollateralContractDate' },
      { kind: 'field', label: 'Сумма требований в реестре:', field: 'ipCollateralClaimAmount', unit: 'руб.' },
      { kind: 'field', label: 'Описание предмета залога:', field: 'mortgageCollateralDescription1221' },
      { kind: 'tpl', label: 'Просроченный долг:', template: '{principalDebt13} руб., проценты {interest14} руб., неустойка {forfeit15} руб.' },
      { kind: 'text', text: 'В комплект входят: принятие РТК с залогом, решение о включении в РТК с залогом, резолютивная часть.' },
    ],
  },
];
